### ISSUE TITLE
Different resolutions for PNG files

### ISSUE THREAD

**Issue by PorlyBe** [theantnest/Bitcoin-Cash-Green-Art#1]
Please add some more PNGs at different resolutions. This would save people having to do conversions themselves (aka ready made resources for websites). I don't need personally need anything specific, but think it could be useful for others. Maybe renders with different heights (64, 128, 256, 512, 1024 etc).

Also, please make a coin logo without the green rectangle background. I know it's not really how it should look but having something square would be handy. These could be used for website/desktop/app icons, etc (128x128, 256x256, 512x512, 1024x1024)

**Comment by theantnest** [comment]
Thanks for the suggestions. I will add the small icons, favicons, etc, as suggested as I do think they are useful.

Also a round logo without the cashnote, I also agree is useful.

Regarding the resize options, there are many free online picture resizing utilities which will give any web designer the precise size needed for their application. I will add links to these in the readme file, although I expect most devs will either have the tools to do resizing themselves, or be aware of the web based options.

I consider this more useful than uploading a bunch of generic sizes which may be close to what is needed for somebody, but not perfect. Much better results will be obtained by using the high res png's already in the repo and converting them to the exact size needed.

**Comment by theantnest** [comment]
Files added. Readme modified.

**Comment by tea-spoon** [comment]
Thanks for these contributions @theantnest @chaintip!

**Comment by chaintip** [comment]
[chaintip](http://www.chaintip.org) has [returned](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4y57a60yjdje3ntjh04d04yrrgjqyfdw8p5a) the unclaimed tip of `0.00333111 BCH`| `~   4.27 USD` to @tea-spoon.
